name: LightTable
options:
  bundleIdPrefix: com.saiday
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
settings:
  base:
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_IDENTITY: "-"
targets:
  LightTable:
    type: application
    platform: macOS
    sources:
      - LightTable
    settings:
      base:
        PRODUCT_NAME: "Light Table"
        PRODUCT_MODULE_NAME: LightTable
        INFOPLIST_FILE: LightTable/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: LightTable/LightTable.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.saiday.light-table
    scheme:
      testTargets:
        - LightTableTests
  LightTableTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - LightTableTests
    dependencies:
      - target: LightTable
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Light Table.app/Contents/MacOS/Light Table"
        GENERATE_INFOPLIST_FILE: YES
